// Generated by scripts/optimize-photos.mjs — do not edit by hand.
export interface Photo {
  file: string
  src: string
  width: number
  height: number
}

export const photos: Photo[] = [
  {
    "file": "DSC00395.jpg",
    "src": "/photography/DSC00395.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00454.jpg",
    "src": "/photography/DSC00454.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00497.jpg",
    "src": "/photography/DSC00497.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00501.jpg",
    "src": "/photography/DSC00501.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00535.jpg",
    "src": "/photography/DSC00535.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00550.jpg",
    "src": "/photography/DSC00550.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00730.jpg",
    "src": "/photography/DSC00730.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00744.jpg",
    "src": "/photography/DSC00744.webp",
    "width": 1200,
    "height": 800
  },
  {
    "file": "DSC00762.jpg",
    "src": "/photography/DSC00762.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00780.jpg",
    "src": "/photography/DSC00780.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00787.jpg",
    "src": "/photography/DSC00787.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00874.jpg",
    "src": "/photography/DSC00874.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00957.jpg",
    "src": "/photography/DSC00957.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC00989.jpg",
    "src": "/photography/DSC00989.webp",
    "width": 1200,
    "height": 1625
  },
  {
    "file": "DSC01181.jpg",
    "src": "/photography/DSC01181.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "DSC01314.jpg",
    "src": "/photography/DSC01314.webp",
    "width": 1200,
    "height": 800
  },
  {
    "file": "DSC01646.jpg",
    "src": "/photography/DSC01646.webp",
    "width": 1200,
    "height": 1800
  },
  {
    "file": "IMG_3074.jpg",
    "src": "/photography/IMG_3074.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "IMG_3338.jpg",
    "src": "/photography/IMG_3338.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "IMG_3412.jpg",
    "src": "/photography/IMG_3412.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "PXL_20231001_115813766.jpg",
    "src": "/photography/PXL_20231001_115813766.webp",
    "width": 1200,
    "height": 900
  },
  {
    "file": "PXL_20231002_154544818.NIGHT.jpg",
    "src": "/photography/PXL_20231002_154544818.NIGHT.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "PXL_20231004_144351787.jpg",
    "src": "/photography/PXL_20231004_144351787.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "PXL_20231005_075511752.jpg",
    "src": "/photography/PXL_20231005_075511752.webp",
    "width": 1200,
    "height": 1942
  },
  {
    "file": "PXL_20231007_122243061.NIGHT.jpg",
    "src": "/photography/PXL_20231007_122243061.NIGHT.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "PXL_20231007_133555925.NIGHT.jpg",
    "src": "/photography/PXL_20231007_133555925.NIGHT.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "file": "PXL_20231007_143448978.MP.jpg",
    "src": "/photography/PXL_20231007_143448978.MP.webp",
    "width": 1200,
    "height": 1616
  },
  {
    "file": "Screenshot 2024-03-06 220320.png",
    "src": "/photography/Screenshot_2024-03-06_220320.webp",
    "width": 952,
    "height": 1268
  }
]
