// Generates web-optimized WebP copies of the photos in src/assets/photography,
// the src/lib/photos.ts manifest used by the photography page, and the
// src/data/captions.json file you edit to caption each photo.
//
// Usage: npm run photos
//
// To unpublish a photo, move its original into src/assets/photography/excluded/
// and re-run — never delete files from public/photography, which is generated
// output that this script overwrites.
//
// Originals are never modified. Existing captions are preserved across runs;
// captions for files that no longer exist are dropped. Files that browsers
// can't decode (e.g. HEIC) are skipped and reported.

import fs from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'

const SRC_DIR = 'src/assets/photography'
const OUT_DIR = 'public/photography'
const MANIFEST = 'src/lib/photos.ts'
const CAPTIONS = 'src/data/captions.json'
const MAX_WIDTH = 1200
const QUALITY = 78
const SUPPORTED = /\.(jpe?g|png)$/i

/** Filesystem-safe output name for a photo. */
function slug(base) {
  return base.replace(/[^A-Za-z0-9._~-]+/g, '_')
}

function readExistingCaptions() {
  if (!fs.existsSync(CAPTIONS)) return {}
  try {
    return JSON.parse(fs.readFileSync(CAPTIONS, 'utf8'))
  } catch {
    console.warn(`could not parse ${CAPTIONS} — starting a fresh file`)
    return {}
  }
}

const existing = readExistingCaptions()

const all = fs
  .readdirSync(SRC_DIR)
  .filter((f) => !f.startsWith('.') && fs.statSync(path.join(SRC_DIR, f)).isFile())
  .sort((a, b) => a.localeCompare(b))

const files = all.filter((f) => SUPPORTED.test(f))
const skipped = all.filter((f) => !SUPPORTED.test(f))

const excludedDir = path.join(SRC_DIR, 'excluded')
const excluded = fs.existsSync(excludedDir)
  ? fs.readdirSync(excludedDir).filter((f) => !f.startsWith('.')).length
  : 0

fs.rmSync(OUT_DIR, { recursive: true, force: true })
fs.mkdirSync(OUT_DIR, { recursive: true })

const entries = []
const captions = {}
let total = 0

for (const file of files) {
  const outName = `${slug(file.replace(/\.[^.]+$/, ''))}.webp`
  const info = await sharp(path.join(SRC_DIR, file))
    .rotate()
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(path.join(OUT_DIR, outName))

  total += info.size
  entries.push({
    file,
    src: `/photography/${outName}`,
    width: info.width,
    height: info.height,
  })
  captions[file] = typeof existing[file] === 'string' ? existing[file] : ''
}

const manifest =
  '// Generated by scripts/optimize-photos.mjs — do not edit by hand.\n' +
  'export interface Photo {\n' +
  '  file: string\n' +
  '  src: string\n' +
  '  width: number\n' +
  '  height: number\n' +
  '}\n\n' +
  `export const photos: Photo[] = ${JSON.stringify(entries, null, 2)}\n`

fs.writeFileSync(MANIFEST, manifest)

fs.mkdirSync(path.dirname(CAPTIONS), { recursive: true })
fs.writeFileSync(CAPTIONS, `${JSON.stringify(captions, null, 2)}\n`)

console.log(`optimized ${entries.length} photos -> ${OUT_DIR} (${(total / 1048576).toFixed(1)} MB)`)
console.log(`manifest -> ${MANIFEST}`)
console.log(`captions -> ${CAPTIONS}`)
if (skipped.length) console.log(`skipped ${skipped.length} unsupported file(s): ${skipped.join(', ')}`)
if (excluded) console.log(`excluded ${excluded} file(s) in ${excludedDir} (not published)`)
